# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: debugger-interface.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import calibration_pb2 as calibration__pb2
import supply_pb2 as supply__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='debugger-interface.proto',
  package='Debugger',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x64\x65\x62ugger-interface.proto\x12\x08\x44\x65\x62ugger\x1a\x0cnanopb.proto\x1a\x11\x63\x61libration.proto\x1a\x0csupply.proto\"\xa5\x03\n\x08Upstream\x12>\n\x14\x63\x61libration_response\x18\x01 \x01(\x0b\x32\x1e.Emulation.CalibrationResponseH\x00\x12\x39\n\x13\x64\x61tastream_response\x18\x02 \x01(\x0b\x32\x1a.Supply.DataStreamResponseH\x00\x12(\n\ndatastream\x18\x03 \x01(\x0b\x32\x12.Supply.DataStreamH\x00\x12\x35\n\x11\x62reakpoint_stream\x18\x04 \x01(\x0b\x32\x18.Supply.BreakpointStreamH\x00\x12-\n\rstatus_stream\x18\x05 \x01(\x0b\x32\x14.Supply.StatusStreamH\x00\x12@\n\x14profile_data_request\x18\x06 \x01(\x0b\x32 .Supply.ProfileDataRequestStreamH\x00\x12\x42\n\x16initial_param_response\x18\x07 \x01(\x0b\x32 .Supply.InitialParameterResponseH\x00\x42\x08\n\x06packet\"\xa9\x03\n\nDownstream\x12<\n\x13\x63\x61libration_request\x18\x01 \x01(\x0b\x32\x1d.Emulation.CalibrationRequestH\x00\x12\x37\n\x12\x64\x61tastream_request\x18\x02 \x01(\x0b\x32\x19.Supply.DataStreamRequestH\x00\x12+\n\x0cmode_request\x18\x03 \x01(\x0b\x32\x13.Supply.ModeRequestH\x00\x12-\n\rpause_request\x18\x04 \x01(\x0b\x32\x14.Supply.PauseRequestH\x00\x12@\n\x14supply_value_request\x18\x05 \x01(\x0b\x32 .Supply.SupplyValueChangeRequestH\x00\x12:\n\x14profile_data_respond\x18\x06 \x01(\x0b\x32\x1a.Supply.ProfileDataRespondH\x00\x12@\n\x15initial_param_request\x18\x07 \x01(\x0b\x32\x1f.Supply.InitialParameterRequestH\x00\x42\x08\n\x06packet'
  ,
  dependencies=[nanopb__pb2.DESCRIPTOR,calibration__pb2.DESCRIPTOR,supply__pb2.DESCRIPTOR,])




_UPSTREAM = _descriptor.Descriptor(
  name='Upstream',
  full_name='Debugger.Upstream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibration_response', full_name='Debugger.Upstream.calibration_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datastream_response', full_name='Debugger.Upstream.datastream_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datastream', full_name='Debugger.Upstream.datastream', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='breakpoint_stream', full_name='Debugger.Upstream.breakpoint_stream', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_stream', full_name='Debugger.Upstream.status_stream', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profile_data_request', full_name='Debugger.Upstream.profile_data_request', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial_param_response', full_name='Debugger.Upstream.initial_param_response', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='packet', full_name='Debugger.Upstream.packet',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=86,
  serialized_end=507,
)


_DOWNSTREAM = _descriptor.Descriptor(
  name='Downstream',
  full_name='Debugger.Downstream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibration_request', full_name='Debugger.Downstream.calibration_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datastream_request', full_name='Debugger.Downstream.datastream_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode_request', full_name='Debugger.Downstream.mode_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pause_request', full_name='Debugger.Downstream.pause_request', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='supply_value_request', full_name='Debugger.Downstream.supply_value_request', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='profile_data_respond', full_name='Debugger.Downstream.profile_data_respond', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial_param_request', full_name='Debugger.Downstream.initial_param_request', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='packet', full_name='Debugger.Downstream.packet',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=510,
  serialized_end=935,
)

_UPSTREAM.fields_by_name['calibration_response'].message_type = calibration__pb2._CALIBRATIONRESPONSE
_UPSTREAM.fields_by_name['datastream_response'].message_type = supply__pb2._DATASTREAMRESPONSE
_UPSTREAM.fields_by_name['datastream'].message_type = supply__pb2._DATASTREAM
_UPSTREAM.fields_by_name['breakpoint_stream'].message_type = supply__pb2._BREAKPOINTSTREAM
_UPSTREAM.fields_by_name['status_stream'].message_type = supply__pb2._STATUSSTREAM
_UPSTREAM.fields_by_name['profile_data_request'].message_type = supply__pb2._PROFILEDATAREQUESTSTREAM
_UPSTREAM.fields_by_name['initial_param_response'].message_type = supply__pb2._INITIALPARAMETERRESPONSE
_UPSTREAM.oneofs_by_name['packet'].fields.append(
  _UPSTREAM.fields_by_name['calibration_response'])
_UPSTREAM.fields_by_name['calibration_response'].containing_oneof = _UPSTREAM.oneofs_by_name['packet']
_UPSTREAM.oneofs_by_name['packet'].fields.append(
  _UPSTREAM.fields_by_name['datastream_response'])
_UPSTREAM.fields_by_name['datastream_response'].containing_oneof = _UPSTREAM.oneofs_by_name['packet']
_UPSTREAM.oneofs_by_name['packet'].fields.append(
  _UPSTREAM.fields_by_name['datastream'])
_UPSTREAM.fields_by_name['datastream'].containing_oneof = _UPSTREAM.oneofs_by_name['packet']
_UPSTREAM.oneofs_by_name['packet'].fields.append(
  _UPSTREAM.fields_by_name['breakpoint_stream'])
_UPSTREAM.fields_by_name['breakpoint_stream'].containing_oneof = _UPSTREAM.oneofs_by_name['packet']
_UPSTREAM.oneofs_by_name['packet'].fields.append(
  _UPSTREAM.fields_by_name['status_stream'])
_UPSTREAM.fields_by_name['status_stream'].containing_oneof = _UPSTREAM.oneofs_by_name['packet']
_UPSTREAM.oneofs_by_name['packet'].fields.append(
  _UPSTREAM.fields_by_name['profile_data_request'])
_UPSTREAM.fields_by_name['profile_data_request'].containing_oneof = _UPSTREAM.oneofs_by_name['packet']
_UPSTREAM.oneofs_by_name['packet'].fields.append(
  _UPSTREAM.fields_by_name['initial_param_response'])
_UPSTREAM.fields_by_name['initial_param_response'].containing_oneof = _UPSTREAM.oneofs_by_name['packet']
_DOWNSTREAM.fields_by_name['calibration_request'].message_type = calibration__pb2._CALIBRATIONREQUEST
_DOWNSTREAM.fields_by_name['datastream_request'].message_type = supply__pb2._DATASTREAMREQUEST
_DOWNSTREAM.fields_by_name['mode_request'].message_type = supply__pb2._MODEREQUEST
_DOWNSTREAM.fields_by_name['pause_request'].message_type = supply__pb2._PAUSEREQUEST
_DOWNSTREAM.fields_by_name['supply_value_request'].message_type = supply__pb2._SUPPLYVALUECHANGEREQUEST
_DOWNSTREAM.fields_by_name['profile_data_respond'].message_type = supply__pb2._PROFILEDATARESPOND
_DOWNSTREAM.fields_by_name['initial_param_request'].message_type = supply__pb2._INITIALPARAMETERREQUEST
_DOWNSTREAM.oneofs_by_name['packet'].fields.append(
  _DOWNSTREAM.fields_by_name['calibration_request'])
_DOWNSTREAM.fields_by_name['calibration_request'].containing_oneof = _DOWNSTREAM.oneofs_by_name['packet']
_DOWNSTREAM.oneofs_by_name['packet'].fields.append(
  _DOWNSTREAM.fields_by_name['datastream_request'])
_DOWNSTREAM.fields_by_name['datastream_request'].containing_oneof = _DOWNSTREAM.oneofs_by_name['packet']
_DOWNSTREAM.oneofs_by_name['packet'].fields.append(
  _DOWNSTREAM.fields_by_name['mode_request'])
_DOWNSTREAM.fields_by_name['mode_request'].containing_oneof = _DOWNSTREAM.oneofs_by_name['packet']
_DOWNSTREAM.oneofs_by_name['packet'].fields.append(
  _DOWNSTREAM.fields_by_name['pause_request'])
_DOWNSTREAM.fields_by_name['pause_request'].containing_oneof = _DOWNSTREAM.oneofs_by_name['packet']
_DOWNSTREAM.oneofs_by_name['packet'].fields.append(
  _DOWNSTREAM.fields_by_name['supply_value_request'])
_DOWNSTREAM.fields_by_name['supply_value_request'].containing_oneof = _DOWNSTREAM.oneofs_by_name['packet']
_DOWNSTREAM.oneofs_by_name['packet'].fields.append(
  _DOWNSTREAM.fields_by_name['profile_data_respond'])
_DOWNSTREAM.fields_by_name['profile_data_respond'].containing_oneof = _DOWNSTREAM.oneofs_by_name['packet']
_DOWNSTREAM.oneofs_by_name['packet'].fields.append(
  _DOWNSTREAM.fields_by_name['initial_param_request'])
_DOWNSTREAM.fields_by_name['initial_param_request'].containing_oneof = _DOWNSTREAM.oneofs_by_name['packet']
DESCRIPTOR.message_types_by_name['Upstream'] = _UPSTREAM
DESCRIPTOR.message_types_by_name['Downstream'] = _DOWNSTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Upstream = _reflection.GeneratedProtocolMessageType('Upstream', (_message.Message,), {
  'DESCRIPTOR' : _UPSTREAM,
  '__module__' : 'debugger_interface_pb2'
  # @@protoc_insertion_point(class_scope:Debugger.Upstream)
  })
_sym_db.RegisterMessage(Upstream)

Downstream = _reflection.GeneratedProtocolMessageType('Downstream', (_message.Message,), {
  'DESCRIPTOR' : _DOWNSTREAM,
  '__module__' : 'debugger_interface_pb2'
  # @@protoc_insertion_point(class_scope:Debugger.Downstream)
  })
_sym_db.RegisterMessage(Downstream)


# @@protoc_insertion_point(module_scope)
