#ifndef PLATFORMS_INT_DEBUG_V1_0_H_
#define PLATFORMS_INT_DEBUG_V1_0_H_

#define EMULATOR_CONFIG_PINS_PORT GPIOA
#define EMULATOR_OUTPUT_EN_PIN GPIO_PIN_0
#define EMULATOR_LDO_EN_PIN GPIO_PIN_2
#define EMULATOR_DISCHARGE_PIN GPIO_PIN_1
#define EMULATOR_LOW_SENSE_BYPASS_PIN GPIO_PIN_3
#define EMULATOR_VIRT_CAP_PIN GPIO_PIN_6

#define DEBUG_EN_PIN_PORT GPIOD
#define DEBUG_LDO_EN_PIN GPIO_PIN_8
#define DEBUG_CONFIG_PINS_PORT GPIOC
#define DEBUG_OUTPUT_EN_PIN GPIO_PIN_13
#define DEBUG_DISCHARGE_PIN GPIO_PIN_14

#define PIN_INT_Pin GPIO_PIN_7
#define PIN_INT_GPIO_Port GPIOB

#define DUT_CURRENT_HIGH_CHANNEL SDADC_CHANNEL_4
#define DUT_CURRENT_LOW_CHANNEL SDADC_CHANNEL_8
#define DUT_VOUT_CHANNEL SDADC_CHANNEL_7
#define DEBUG_VOUT_CHANNEL SDADC_CHANNEL_8

void systemConfig(void);

#endif /* PLATFORMS_INT_DEBUG_V1_0_H_ */
