#ifndef LIBS_SPI_SPI_DBG_H_
#define LIBS_SPI_SPI_DBG_H_

#include "platform.h"

#define BUFFER_SIZE 4
// MODES:
#define SUPPLY_MODE_BEAT 0x00
#define SUPPLY_MODE_CONTINUES 0x01
#define SUPPLY_MODE_BREAKPOINT 0x02
#define SUPPLY_MODE_ENERGY_THRESHOLD 0x03
#define SUPPLY_MODE_ENERGY_BREAKPOINT 0x04
#define SUPPLY_MODE_INTERMIT_NEXT_LINE 0x05
#define SUPPLY_MODE_COMPENSATE 0x06

// PARAMS:
#define SUPPLY_PARAM_RESERVED 0x00
#define SUPPLY_PARAM_BREAKPOINT 0x01
#define SUPPLY_PARAM_WATCHPOINT 0x02
#define SUPPLY_PARAM_SET 0x03
#define SUPPLY_PARAM_CLEAR 0x04
#define SUPPLY_PARAM_OTHER 0xFF

void spiDbgConfig(void);
void sendSPI(void);

#endif /* LIBS_SPI_SPI_DBG_H_ */
